CREATE DATABASE GREENCONNECT_DB;
USE GREENCONNECT_DB;
DROP TABLE USUARIO;
CREATE TABLE USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    IMAGEM LONGTEXT,
    EMAIL VARCHAR(255),
    SENHA VARCHAR(255)
);
